---
image_tag: "build"
image_name: "opencontrailnightly/developer-sandbox"
sandbox_branch: "{{ zuul.branch }}"
workdir: '{{ zuul.projects | selectattr("short_name", "equalto", "tf-dev-env") | map(attribute="src_dir") | list | first }}'

