---
contrail_package_repository: "http://{{ zuul_site_mirror_fqdn }}/repository/{{ packaging.repo_names[ansible_distribution] }}/"
contrail_version: "{{ packaging.repo_name }}"
openstack_version:
  - ocata
  - newton
  - queens
  - rocky
rpm_repo_config_dir: /etc/yum.repos.d/
test_container_build_dir: "{{ ansible_env.HOME }}/src/{{ zuul.project.canonical_hostname }}/Juniper/contrail-test"

